MaxResets: 3

Levels: #BlocksToMine
  - 50
  - 100
  - 200
  - 350
  - 500

Tradings: #This is the inventory where all inventories go
  Name: '&8Tradings...'
  Size: 27
  Items:
    1:
      Name: '&aBlocks'
      Lore:
        - ''
      Material: 'GRASS'
      Data: 0
      Slot: 10
      Inventory: 1 #Inventory to open (Key name must be the same) (If not exist it wont open)

TradingInventories:
  1: #You can create multiple inventories for trading
    Name: '&8Blocks...' #Inventory name
    Size: 36
    Items:
      1: #This is the item that will given to player
        Name: ''
        Lore:
          - ''
        Material: 'GRASS'
        Data: 0
        Slot: 10
        TradeItem: #This item is the needed to change
          Name: '' #Leave blank if you don't want custom name
          Lore:
            - ''
          Material: 'COBBLESTONE'
          Data: 0

TabList:
  Header:
    - ''
  Footer:
    - ''

Scoreboard:
  Title: ''
  List:
    - ''

Inventories:
  TopMenu:
    Name: '&8TopMenu...'
    Items:
      Name: '&aTop &e#%number% &7&o(%player%)'
      Lore:
        - '&f%level%'
      Material: 'SKULL_ITEM'
      Data: 3
  KickPlayer:
    Name: '&8KickPlayer...'
    Items:
      Name: '&a%player%'
      Lore:
        - ''
      Material: 'SKULL_ITEM'
      Data: 3
  AddPlayer:
    Name: '&8AddPlayer...'
    Items:
      Name: '&a%player%'
      Lore:
        - ''
      Material: 'SKULL_ITEM'
      Data: 3
  IsMenu:
    Name: '&8Settings...'
    Size: 9
    Items:
      Spawn:
        Name: '&aSpawn'
        Lore:
          - ''
        Material: 'BED'
        Data: 0
        Slot: 0
      TopIslands:
        Name: '&aTop Islands'
        Lore:
          - ''
        Material: 'DIAMOND_SWORD'
        Data: 0
        Slot: 1
      ResetIsland:
        Name: '&aReset Island'
        Lore:
          - ''
        Material: 'NETHER_STAR'
        Data: 0
        Slot: 2
      KickPlayer:
        Name: '&aKick Player'
        Lore:
          - ''
        Material: 'REDSTONE'
        Data: 0
        Slot: 3
      LockIsland:
        Name: '&aLock Island'
        Lore:
          - ''
        Material: 'BARRIER'
        Data: 0
        Slot: 4
      AddPlayer:
        Name: '&aAdd Player'
        Lore:
          - ''
        Material: 'EMERALD_BLOCK'
        Data: 0
        Slot: 5
      IslandLevel:
        Name: '&aIsland Level'
        Lore:
          - ''
        Material: 'LAVA_BUCKET'
        Data: 0
        Slot: 6
      IslandChat:
        Name: '&aIsland Chat'
        Lore:
          - ''
        Material: 'PAPER'
        Data: 0
        Slot: 7